server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
     defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul: 
  #ignored-services: microservicecloud-dept
#  prefix: /xiao
  ignored-services: "*"  #禁止微服务名直接访问
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
#    mydept2.serviceId: microservicecloud-dept
#    mydept3.path: /mydept2/**
info:
  app.name: microcloud
  company.name: xiao.yang


